### PR TITLE
Style and help modal update

### PR DESCRIPTION
**Pull request by DanielSeehausen**

### CODE REVIEW

**Comment by DanielSeehausen** [comment]
pending @Gonzodamus approval

**Comment by Dick-Ward** [comment]
I've incorporated a lot of the stylistic changes from this into a new PR.  This request breaks the zoom and contains a few redundancies, like the modal. It looks like you did a lot of organization/deletion though.  Rather than update this one (which I would recommend closing), it seems better for organization that this all be done in a separate PR.

**Comment by realAndrewCohn** [comment]
Does #71 address everything from this PR? If so, can we close?

@Gonzodamus 
@DanielSeehausen

**Comment by DanielSeehausen** [comment]
sorry for the lack of communication here - both dick and I were mindmelding and writing stuff at the same time (uncanny really, as a lot of the stuff was literally exactly the same). if you can, clone this one down and take a look at the help modal action. if you don't like it we can move it to the bottom right, but my hope was that it is something that is only up for a quick reference then gone again just as easily. want to keep the board as sexy and pure looking as possible.

**Comment by DanielSeehausen** [comment]
image

**Comment by DanielSeehausen** [comment]
actually changed font take a look at this one:

image

**Comment by DanielSeehausen** [comment]
the ? with circle that you added (svg) is still there, just fades out on click, and back in on unfocus of the help menu

**Comment by Dick-Ward** [comment]
Personally I would rather have the instructions out of the way for quick reference.  That way I can have them open if I want.  The center modal gives you no choice but to interrupt what you're doing to reference the keybindings.

If you really insist on center, it should be able to be closed by clicking on it.  Currently it's a little unintuitive

**Comment by DanielSeehausen** [comment]
ok @Gonzodamus excellent points -- will move it, remove the hide on blur functionality, and add in the X at the top.

**Comment by DanielSeehausen** [comment]
(before saturday)

**Comment by realAndrewCohn** [comment]
are we good to delete this branch since it's been merged in?

**Pull request merged**
