### PR TITLE
Netstat react app

### PR DESCRIPTION
**Pull request by bruugey**

### CODE REVIEW

**Comment by realAndrewCohn** [comment]
The dankness of this PR knows no bounds

bitmoji

**Review by realAndrewCohn — APPROVED** [review]
A M A Z I N G

**Review by DanielSeehausen — APPROVED** [review]
top! great work guys! plus brandon as reviewer is A++

**Comment by realAndrewCohn** [comment]
Going to take another pass and refactor 2nite but it's looking pretty D A N K atm

**Pull request merged**
